version: '2'
services:

  memcached:
    image: memcached
    mem_limit: 1g
    command: memcached -m 1024m
    ports: ["11211"]

  redis:
    image: redis
    ports: ["6379"]

  nginx:
    build:
      context: ./environment/nginx
    volumes_from: ["php"]
    depends_on: ["php"]
    volumes:
      - ./environment/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80

  php:
    depends_on: ["mysql"]
    build:
      context: ./environment/php
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:5.7
    volumes:
      - ./environment/mysql/sql:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 33061:3306

volumes:
  dbdata:
