version: '3.2'
services:

  memcached:
    image: memcached
    networks:
      static-network:
        ipv4_address: 172.16.200.2

  redis:
    image: redis
    networks:
      static-network:
        ipv4_address: 172.16.200.3

  nginx:
    build:
      context: ./environment/nginx
    depends_on: ["php"]
    volumes:
      - ./environment/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    networks:
      static-network:
        ipv4_address: 172.16.200.4

  php:
    depends_on: ["mysql"]
    build:
      context: ./environment/php
    volumes:
      - ./:/var/www/html
    networks:
      static-network:
        ipv4_address: 172.16.200.5

  mysql:
    image: mysql:5.7
    volumes:
      - ./environment/mysql/sql:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root

volumes:
  dbdata:

networks:
  static-network:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.200.0/24
